# Generated by Django 3.0.3 on 2020-02-10 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
